### ISSUE TITLE
Crash when create a VS without input stream

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#13]
```
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime: Process: tinygsn.gui.android, PID: 3522
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:304)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to get length of null array
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.controller.AndroidControllerVS.loadLatestData(AndroidControllerVS.java:66)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.controller.AndroidControllerVS.loadLatestData(AndroidControllerVS.java:55)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.gui.android.ActivityListVS$4.doInBackground(ActivityListVS.java:156)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.gui.android.ActivityListVS$4.doInBackground(ActivityListVS.java:153)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
10-02 23:19:37.756 3522-4130/tinygsn.gui.android E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by AblionGE** [comment]
Probably need to do a test before continuing to save the VS

**Comment by ebiiii** [comment]
I think it would be better to make the method loadLatestData allowing the VS to return null when asking for the output structure (https://github.com/AblionGE/gsn/blob/maschaer_semester_project/gsn-tiny/app/src/main/java/tinygsn/controller/AndroidControllerVS.java#L65). There are other cases which could lead to that. 
But it is also a good idea to check for the VS input.

**Comment by AblionGE** [comment]
done
