### ISSUE TITLE
VSensorConfig is never created

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#17]
`VSensorConfig` is never created but used by NotificationVS. It crashes because fields are never set.

**Comment by AblionGE** [comment]
``````
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.model.vsensor.NotificationVirtualSensor.dataAvailable(NotificationVirtualSensor.java:93)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.model.vsensor.AbstractVirtualSensor.dataAvailable(AbstractVirtualSensor.java:209)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.beans.StreamSource.notifyInputStream(StreamSource.java:138)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.beans.StreamSource.add(StreamSource.java:84)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.model.wrappers.AbstractWrapper.postStreamElement(AbstractWrapper.java:179)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at tinygsn.model.wrappers.AndroidLightWrapper.onSensorChanged(AndroidLightWrapper.java:111)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at android.os.MessageQueue.nativePollOnce(Native Method)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at android.os.MessageQueue.next(MessageQueue.java:143)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:122)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-06 14:08:22.754 25955-25955/tinygsn.gui.android E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
``````

**Comment by AblionGE** [comment]
Solution: get fields from DB
