### ISSUE TITLE
Bug when activate Location Scheduler

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#8]
```
09-26 15:12:47.267    1102-4228/tinygsn.gui.android W/System.err﹕ java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
09-26 15:12:47.277    1102-4228/tinygsn.gui.android W/System.err﹕ at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
09-26 15:12:47.277    1102-4228/tinygsn.gui.android W/System.err﹕ at java.util.ArrayList.get(ArrayList.java:308)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at tinygsn.services.LocationScheduler.runOnce(LocationScheduler.java:92)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at tinygsn.services.WrapperService.onHandleIntent(WrapperService.java:32)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
09-26 15:12:47.297    1102-4228/tinygsn.gui.android W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ebiiii** [comment]
maybe it can be more verbose and explanatory: the location scheduler needs to have 3 VS (bridges) running: accelerometer, GPS and wifi.

**Comment by AblionGE** [comment]
Mmmmmh, I'll investigate if it is possible to have an alarm message when activate it (to inform the user of that)

**Comment by AblionGE** [comment]
I made a Toast and now try to deactivate the wrapper when there is the exception

**Comment by AblionGE** [comment]
I found a way to click on the switch when the exception occurs.
