### ISSUE TITLE
Crash when add a NotificationVS

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#9]
```
09-26 22:38:34.632  11065-14315/tinygsn.gui.android E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #3
    Process: tinygsn.gui.android, PID: 11065
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.Spinner.getSelectedItem()' on a null object reference
            at tinygsn.gui.android.ActivityVSConfig.saveVS(ActivityVSConfig.java:364)
            at tinygsn.gui.android.ActivityVSConfig$6.doInBackground(ActivityVSConfig.java:433)
            at tinygsn.gui.android.ActivityVSConfig$6.doInBackground(ActivityVSConfig.java:430)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

This bug were already present before start working on #4

**Comment by ebiiii** [comment]
all the fields and spinner for selecting the parameters for the notification have to be removed (also from the database schema).
